### ISSUE TITLE
请求提高 "次数上限" 

### ISSUE THREAD

**Issue by ghost** [zyfworks/steam-key#2]
### 服务器:

https://cn1.stkey.win/

### 描述:

发现激活超过10个key会显示 `次数上限` 然后激活失败. (图1)
实际上我的账户并没有 RateLimited.
我用小号测试, 激活了11个key, 其中有一个重复的, 最后激活失败的第11个key 第二次激活也成功了. (图2)

所以, 能否看一下是什么造成了次数限制, 并且提高一下呢?

### 截图:

1. http://imgur.com/a/44RHo
2. http://imgur.com/a/6KZjL

**Comment by makazeu** [comment]
这个限制不是我做的，而是Valve官方做的。

实际上，只有在数秒之内激活超过10个key才会RateLimited，只要两次批量激活之间的间隔10秒左右，即可绕过此限制。我猜你用小号测试的时候，肯定不是一瞬间激活11个key的，之间肯定有时间间隔。

你可以先批量激活9个，然后等个10秒，再激活9个，实测这样就不会被限制。
