### ISSUE TITLE
合作提供一台国内服务器

### ISSUE THREAD

**Issue by FantWings** [zyfworks/steam-key#5]
身边有一台比较空闲的服务器（广州），为了可以更好的加以利用多余的性能，如果有需要可以为你提供南部地区的一部分线路支持，因为在家里，所以只要不介意没有80端口就好（用HTTPS）。

![qq 20171119181307](https://user-images.githubusercontent.com/18146816/32989652-53591c8a-cd55-11e7-87f7-7add471bbfb8.png)

**Comment by makazeu** [comment]
感谢支持，不过最近不太缺服务器，目前国内服务器已经3台了，暂时不需要新的了。。
