### ISSUE TITLE
请问下云服务器有部署的说明吗？

### ISSUE THREAD

**Issue by hkfires** [zyfworks/steam-key#7]
想自己部署一个，不知道能否提供部署说明呢？谢谢！

**Comment by makazeu** [comment]
项目里有Dockerfile，会Docker的话直接就部署了

不会Docker的话手动部署:
1. 安装新版本的Node.js https://nodejs.org/zh-cn/
2. 拉取代码 git clone https://github.com/zyfworks/steam-key.git
3. 进入目录后执行npm install安装依赖
4. 复制一份serverconfig.example.json为serverconfig.json
5. 运行 npm start

**Comment by z4jst** [comment]
docker 编译方法如下：

cd steam-key
docker build -t stkey .  (后面要有点)
docker run -d -p 80:3999 --name stkey (前面为外网访问端口，后面为 stkey 的内部端口。3999 不能改)
